<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('reports')->insert([
            [
                'user_id' => 2,
                'location_id' => 1,
                'report_status_id' => 2,
                'description' => 'Iphone 15 warna hitam.',
                'image' => 'images/1733564014_iphone_black.jpg',
                'is_verified' => false,
                'location_lost' => 'Collab room A di atas meja',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 2,
                'report_status_id' => 2,
                'description' => 'Samsung S24 warna silver.',
                'image' => 'images/samsung24.jpeg',
                'is_verified' => false,
                'location_lost' => 'Meja baris kedua dari depan',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 3,
                'report_status_id' => 2,
                'description' => 'Laptop ASUS warna silver.',
                'image' => 'images/asus.jpeg',
                'is_verified' => false,
                'location_lost' => 'Kursi paling belakang',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 4,
                'report_status_id' => 2,
                'description' => 'Jaket kuning.',
                'image' => 'images/jaketkuning.jpeg',
                'is_verified' => false,
                'location_lost' => 'Dekat carnival jualan kentang',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 5,
                'report_status_id' => 2,
                'description' => 'Tas gentle woman.',
                'image' => 'images/tasg.jpeg',
                'is_verified' => false,
                'location_lost' => 'Kursi belakang FOH',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 1,
                'report_status_id' => 2,
                'description' => 'Iphone 15 warna pink.',
                'image' => 'images/pink.jpeg',
                'is_verified' => false,
                'location_lost' => 'Collab room B',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 2,
                'report_status_id' => 2,
                'description' => 'Samsung S24 warna hitam.',
                'image' => 'images/s24.jpeg',
                'is_verified' => false,
                'location_lost' => 'Meja baris keempat dari depan',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 3,
                'report_status_id' => 2,
                'description' => 'Laptop LEGION warna hitam.',
                'image' => 'images/legion.jpeg',
                'is_verified' => false,
                'location_lost' => 'Kursi paling depan',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 3,
                'report_status_id' => 2,
                'description' => 'Laptop merk HP warna silver.',
                'image' => 'images/hp.jpeg',
                'is_verified' => false,
                'location_lost' => 'Kursi kedua dari depan',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 4,
                'report_status_id' => 2,
                'description' => 'Jaket hijau.',
                'image' => 'images/jakethijau.jpeg',
                'is_verified' => false,
                'location_lost' => 'Dekat depot mapan',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'location_id' => 5,
                'report_status_id' => 2,
                'description' => 'Tas GUCCI.',
                'image' => 'images/gucci.jpeg',
                'is_verified' => false,
                'location_lost' => 'Backstage auditorium',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'location_id' => 2,
                'report_status_id' => 2,
                'description' => 'Kotak pensil kain warna biru.',
                'image' => 'images/Tepak_Pensil.jpg',
                'is_verified' => false,
                'location_lost' => 'Meja Lab SI berisan ke tiga dari depan',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'location_id' => 3,
                'report_status_id' => 2,
                'description' => 'Anting emas bentuk bunga.',
                'image' => 'images/anting.jpg',
                'is_verified' => false,
                'location_lost' => 'Meja barisan ke kelima dari belakang',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'location_id' => 4,
                'report_status_id' => 2,
                'description' => 'Buku tulis merah.',
                'image' => 'images/buku.jpg',
                'is_verified' => false,
                'location_lost' => 'Meja depan stan carnival',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'location_id' => 5,
                'report_status_id' => 2,
                'description' => 'Kalung emas berbentuk air drop.',
                'image' => 'images/kalung.jpg',
                'is_verified' => false,
                'location_lost' => 'Sisi kiri auditorium, barisan ke tiga dari depan',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'location_id' => 1,
                'report_status_id' => 2,
                'description' => 'Kertas jawaban ujian WFD.',
                'image' => 'images/kertas.jpg',
                'is_verified' => false,
                'location_lost' => 'Collab room B di atas meja',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'location_id' => 2,
                'report_status_id' => 2,
                'description' => 'Kunci rumah warna silver dan ada gantungan rumahnya.',
                'image' => 'images/kunci.jpg',
                'is_verified' => false,
                'location_lost' => 'Di atas meja, barisan ke dua dari depan',
                'time_lost' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
